language: nix

env:
  global:
    - STATE_VERSION=19.09

script:
- echo "{ imports = [ ./test-hardware-configuration.nix ./machines/ati.nix ]; system.stateVersion = \"$STATE_VERSION\"; }" > test-configuration.nix
- >
  nix build -f '<nixpkgs/nixos>' system --show-trace
  -I nixpkgs=https://nixos.org/channels/nixos-$STATE_VERSION/nixexprs.tar.xz
  -I nixos-hardware=https://github.com/NixOS/nixos-hardware/archive/master.tar.gz
  -I home-manager=https://github.com/rycee/home-manager/archive/release-$STATE_VERSION.tar.gz
  -I nixos-config=test-configuration.nix
